### ISSUE TITLE
Versions since 7.0.0 give sometimes-invalid hash for CN-haven

### ISSUE THREAD

**Issue by jagerman** [MoneroOcean/node-cryptonight-hashing#28]
Using identical pool code (actually using stock dvandal pool, but I don't think that matters) and identical xmr-stak, if I use v7.0.0 or newer I get roughly 50% of CN-haven hashes get rejected by the pool because node-cryptonight-hashing is giving a hash that differs from what the miner submitted.

Downgrading to v6.0.3 and 100% of submitted hashes are good.

**Comment by MoneroOcean** [comment]
Can you please check if latest xmrig also has the same issue?

**Comment by jagerman** [comment]
xmr-node-proxy has the same issue -- it also rejects miner shares (without them hitting the pool at all) with >= 7.0.0, but works with 6.0.3.

With xmrig 2.15.3-beta, I get the same problem (some accepted, some rejected shares using either xmr-node-proxy or the pool with 9.0.1, but shares are good with 6.0.3).

**Comment by MoneroOcean** [comment]
What is "cat /proc/cpuinfo" on your host?

**Comment by jagerman** [comment]
```
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 1
model name	: AMD Ryzen 7 1700 Eight-Core Processor
stepping	: 1
microcode	: 0x8001137
cpu MHz		: 1374.722
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 7586.02
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]
```

**Comment by bobbieltd** [comment]
+1. Same problem on one of my servers. Inconsistent shares validation with CN Haven.

**Comment by MoneroOcean** [comment]
@bobbieltd also AMD server? Looks like yes, since you have 3dnow

**Comment by MoneroOcean** [comment]
@jagerman did you run xmrig on the same AMD server or it was separate Intel based one?

**Comment by MoneroOcean** [comment]
I put likely fixed version as v9.0.2. Could you please check that it solves the issue?

**Comment by jagerman** [comment]
Confirmed fixed for me under 9.0.2.

**Comment by apstasen** [comment]
Thank you!

**Comment by Alecient** [comment]
+1 Thanks! It also fixes it for me.

**Comment by bobbieltd** [comment]
Confirmed from my side, too. No more cn-haven bad shares from hashing utils. 
MoneroOcean ! Keep up your great work ! Thanks !

**Comment by MoneroOcean** [comment]
@jagerman @Alecient @bobbieltd Thank you for checking!
