### ISSUE TITLE
Latest release - AMD CPU unsupport - ../multihashing.cc:31:6: error: #error Unknown ASM implementation!

### ISSUE THREAD

**Issue by bobbieltd** [MoneroOcean/node-cryptonight-hashing#34]
Hi MO !
Thanks alot for your great work. I have errors when install on AMD EPYC.
Ubuntu 18.04
/proc/cpuinfo
processor       : 7
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC 7401P 24-Core Processor
stepping        : 2
microcode       : 0x1000065
cpu MHz         : 1996.244
cache size      : 512 KB
physical id     : 7
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 ibpb arat npt nrip_save
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips        : 3992.48
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

Error logs :+1: 
../multihashing.cc:31:6: error: #error Unknown ASM implementation!
     #error Unknown ASM implementation!
      ^~~~~
cryptonight-hashing.target.mk:181: recipe for target 'Release/obj.target/cryptonight-hashing/multihashing.o' failed
make: *** [Release/obj.target/cryptonight-hashing/multihashing.o] Error 1
make: Leaving directory '/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.93-mainline-rev1
gyp ERR! command "/home/pooldaemon/.nvm/versions/node/v8.16.0/bin/node" "/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@13.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@13.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by MoneroOcean** [comment]
Is there some errors before? Something bash related?

**Comment by bobbieltd** [comment]
More log : 
~$ npm i -g https://github.com/MoneroOcean/node-cryptonight-hashing

> cryptonight-hashing@13.0.0 install /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing
> node-gyp rebuild

make: Entering directory '/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/build'
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/cn/asm/cn_main_loop.o
  CC(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/cn/asm/CryptonightR_template.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/cn/r/CryptonightR_gen.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/cn/gpu/cn_gpu_avx.o
  CXX(target) Release/obj.target/cryptonight-hashing/xmrig/crypto/cn/gpu/cn_gpu_ssse3.o
  CXX(target) Release/obj.target/cryptonight-hashing/multihashing.o
../multihashing.cc:31:6: error: #error Unknown ASM implementation!
     #error Unknown ASM implementation!
      ^~~~~
cryptonight-hashing.target.mk:181: recipe for target 'Release/obj.target/cryptonight-hashing/multihashing.o' failed
make: *** [Release/obj.target/cryptonight-hashing/multihashing.o] Error 1
make: Leaving directory '/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.93-mainline-rev1
gyp ERR! command "/home/pooldaemon/.nvm/versions/node/v8.16.0/bin/node" "/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonight-hashing@13.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonight-hashing@13.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pooldaemon/.npm/_logs/2019-08-19T21_02_58_037Z-debug.log

/home/pooldaemon/.npm/_logs/2019-08-19T21_02_58_037Z-debug.log : 
0 info it worked if it ends with ok
1 verbose cli [ '/home/pooldaemon/.nvm/versions/node/v8.16.0/bin/node',
1 verbose cli   '/home/pooldaemon/.nvm/versions/node/v8.16.0/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'https://github.com/MoneroOcean/node-cryptonight-hashing' ]
2 info using npm@6.10.3
3 info using node@v8.16.0
4 verbose npm-session 2303867147962606
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 info lifecycle cryptonight-hashing@13.0.0~prepack: cryptonight-hashing@13.0.0
8 info lifecycle cryptonight-hashing@13.0.0~postpack: cryptonight-hashing@13.0.0
9 silly pacote git manifest for undefined@git+https://github.com/MoneroOcean/node-cryptonight-hashing.git fetched in 6110ms
10 timing stage:loadCurrentTree Completed in 6246ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule cryptonight-hashing@13.0.0 checking installable status
18 http fetch GET 304 https://registry.npmjs.org/nan 840ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/bindings 866ms (from cache)
20 silly pacote range manifest for nan@^2.8.0 fetched in 876ms
21 silly resolveWithNewModule nan@2.14.0 checking installable status
22 silly pacote range manifest for bindings@* fetched in 900ms
23 silly resolveWithNewModule bindings@1.5.0 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/file-uri-to-path 203ms (from cache)
25 silly pacote version manifest for file-uri-to-path@1.0.0 fetched in 220ms
26 silly resolveWithNewModule file-uri-to-path@1.0.0 checking installable status
27 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1170ms
28 timing stage:loadIdealTree Completed in 1182ms
29 silly currentTree lib
30 silly idealTree lib
30 silly idealTree └─┬ cryptonight-hashing@13.0.0
30 silly idealTree   ├── bindings@1.5.0
30 silly idealTree   ├── file-uri-to-path@1.0.0
30 silly idealTree   └── nan@2.14.0
31 silly install generateActionsToTake
32 timing stage:generateActionsToTake Completed in 34ms
33 silly diffTrees action count 4
34 silly diffTrees add file-uri-to-path@1.0.0
35 silly diffTrees add bindings@1.5.0
36 silly diffTrees add nan@2.14.0
37 silly diffTrees add cryptonight-hashing@13.0.0
38 silly decomposeActions action count 32
39 silly decomposeActions fetch file-uri-to-path@1.0.0
40 silly decomposeActions extract file-uri-to-path@1.0.0
41 silly decomposeActions preinstall file-uri-to-path@1.0.0
42 silly decomposeActions build file-uri-to-path@1.0.0
43 silly decomposeActions install file-uri-to-path@1.0.0
44 silly decomposeActions postinstall file-uri-to-path@1.0.0
45 silly decomposeActions finalize file-uri-to-path@1.0.0
46 silly decomposeActions refresh-package-json file-uri-to-path@1.0.0
47 silly decomposeActions fetch bindings@1.5.0
48 silly decomposeActions extract bindings@1.5.0
49 silly decomposeActions preinstall bindings@1.5.0
50 silly decomposeActions build bindings@1.5.0
51 silly decomposeActions install bindings@1.5.0
52 silly decomposeActions postinstall bindings@1.5.0
53 silly decomposeActions finalize bindings@1.5.0
54 silly decomposeActions refresh-package-json bindings@1.5.0
55 silly decomposeActions fetch nan@2.14.0
56 silly decomposeActions extract nan@2.14.0
57 silly decomposeActions preinstall nan@2.14.0
58 silly decomposeActions build nan@2.14.0
59 silly decomposeActions install nan@2.14.0
60 silly decomposeActions postinstall nan@2.14.0
61 silly decomposeActions finalize nan@2.14.0
62 silly decomposeActions refresh-package-json nan@2.14.0
63 silly decomposeActions fetch cryptonight-hashing@13.0.0
64 silly decomposeActions extract cryptonight-hashing@13.0.0
65 silly decomposeActions preinstall cryptonight-hashing@13.0.0
66 silly decomposeActions build cryptonight-hashing@13.0.0
67 silly decomposeActions install cryptonight-hashing@13.0.0
68 silly decomposeActions postinstall cryptonight-hashing@13.0.0
69 silly decomposeActions finalize cryptonight-hashing@13.0.0
70 silly decomposeActions refresh-package-json cryptonight-hashing@13.0.0
71 silly install executeActions
72 silly doSerial global-install 32
73 verbose correctMkdir /home/pooldaemon/.npm/_locks correctMkdir not in flight; initializing
74 verbose lock using /home/pooldaemon/.npm/_locks/staging-c4c1dbeebd01adb6.lock for /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/.staging
75 silly doParallel extract 4
76 silly extract file-uri-to-path@1.0.0
77 silly extract bindings@1.5.0
78 silly extract nan@2.14.0
79 silly extract cryptonight-hashing@13.0.0
80 silly tarball trying file-uri-to-path@1.0.0 by hash: sha512-0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==
81 silly tarball trying bindings@* by hash: sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==
82 silly tarball trying nan@^2.8.0 by hash: sha512-INOFj37C7k3AfaNTtX8RhsTw7qRy7eLET14cROi9+5HAVbbHuIWUHEauBv5qT4Av2tWasiTY1Jw6puUNqRJXQg==
83 silly tarball no local data for git+https://github.com/MoneroOcean/node-cryptonight-hashing.git. Extracting by manifest.
84 silly extract bindings@* extracted to /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/.staging/bindings-71aad7f1 (267ms)
85 silly extract file-uri-to-path@1.0.0 extracted to /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/.staging/file-uri-to-path-a5d93df8 (283ms)
86 silly extract nan@^2.8.0 extracted to /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/.staging/nan-b281345d (447ms)
87 info lifecycle cryptonight-hashing@13.0.0~prepack: cryptonight-hashing@13.0.0
88 info lifecycle cryptonight-hashing@13.0.0~postpack: cryptonight-hashing@13.0.0
89 silly extract git+https://github.com/MoneroOcean/node-cryptonight-hashing.git extracted to /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/.staging/cryptonight-hashing-61ea75da (7887ms)
90 timing action:extract Completed in 7916ms
91 silly doReverseSerial unbuild 32
92 silly doSerial remove 32
93 silly doSerial move 32
94 silly doSerial finalize 32
95 silly finalize /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules/file-uri-to-path
96 silly finalize /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules/bindings
97 silly finalize /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules/nan
98 silly finalize /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing
99 timing action:finalize Completed in 145ms
100 silly doParallel refresh-package-json 4
101 silly refresh-package-json /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules/file-uri-to-path
102 silly refresh-package-json /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules/bindings
103 silly refresh-package-json /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules/nan
104 silly refresh-package-json /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing
105 timing action:refresh-package-json Completed in 170ms
106 silly doParallel preinstall 4
107 silly preinstall file-uri-to-path@1.0.0
108 info lifecycle file-uri-to-path@1.0.0~preinstall: file-uri-to-path@1.0.0
109 silly preinstall bindings@1.5.0
110 info lifecycle bindings@1.5.0~preinstall: bindings@1.5.0
111 silly preinstall nan@2.14.0
112 info lifecycle nan@2.14.0~preinstall: nan@2.14.0
113 silly preinstall cryptonight-hashing@13.0.0
114 info lifecycle cryptonight-hashing@13.0.0~preinstall: cryptonight-hashing@13.0.0
115 timing action:preinstall Completed in 26ms
116 silly doSerial build 32
117 silly build file-uri-to-path@1.0.0
118 info linkStuff file-uri-to-path@1.0.0
119 silly linkStuff file-uri-to-path@1.0.0 has /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules as its parent node_modules
120 silly linkStuff file-uri-to-path@1.0.0 is part of a global install
121 silly linkStuff file-uri-to-path@1.0.0 is installed into a global node_modules
122 silly build bindings@1.5.0
123 info linkStuff bindings@1.5.0
124 silly linkStuff bindings@1.5.0 has /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules as its parent node_modules
125 silly linkStuff bindings@1.5.0 is part of a global install
126 silly linkStuff bindings@1.5.0 is installed into a global node_modules
127 silly build nan@2.14.0
128 info linkStuff nan@2.14.0
129 silly linkStuff nan@2.14.0 has /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules as its parent node_modules
130 silly linkStuff nan@2.14.0 is part of a global install
131 silly linkStuff nan@2.14.0 is installed into a global node_modules
132 silly build cryptonight-hashing@13.0.0
133 info linkStuff cryptonight-hashing@13.0.0
134 silly linkStuff cryptonight-hashing@13.0.0 has /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules as its parent node_modules
135 silly linkStuff cryptonight-hashing@13.0.0 is part of a global install
136 silly linkStuff cryptonight-hashing@13.0.0 is installed into a global node_modules
137 silly linkStuff cryptonight-hashing@13.0.0 is installed into the top-level global node_modules
138 timing action:build Completed in 17ms
139 silly doSerial global-link 32
140 silly doParallel update-linked 0
141 silly doSerial install 32
142 silly install file-uri-to-path@1.0.0
143 info lifecycle file-uri-to-path@1.0.0~install: file-uri-to-path@1.0.0
144 silly install bindings@1.5.0
145 info lifecycle bindings@1.5.0~install: bindings@1.5.0
146 silly install nan@2.14.0
147 info lifecycle nan@2.14.0~install: nan@2.14.0
148 silly install cryptonight-hashing@13.0.0
149 info lifecycle cryptonight-hashing@13.0.0~install: cryptonight-hashing@13.0.0
150 verbose lifecycle cryptonight-hashing@13.0.0~install: unsafe-perm in lifecycle true
151 verbose lifecycle cryptonight-hashing@13.0.0~install: PATH: /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing/node_modules/.bin:/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/.bin:/home/pooldaemon/.nvm/versions/node/v8.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
152 verbose lifecycle cryptonight-hashing@13.0.0~install: CWD: /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/cryptonight-hashing
153 silly lifecycle cryptonight-hashing@13.0.0~install: Args: [ '-c', 'node-gyp rebuild' ]
154 silly lifecycle cryptonight-hashing@13.0.0~install: Returned: code: 1  signal: null
155 info lifecycle cryptonight-hashing@13.0.0~install: Failed to exec install script
156 timing action:install Completed in 11607ms
157 verbose unlock done using /home/pooldaemon/.npm/_locks/staging-c4c1dbeebd01adb6.lock for /home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/.staging
158 timing stage:rollbackFailedOptional Completed in 606ms
159 timing stage:runTopLevelLifecycles Completed in 27987ms
160 verbose stack Error: cryptonight-hashing@13.0.0 install: `node-gyp rebuild`
160 verbose stack Exit status 1
160 verbose stack     at EventEmitter.<anonymous> (/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
160 verbose stack     at emitTwo (events.js:126:13)
160 verbose stack     at EventEmitter.emit (events.js:214:7)
160 verbose stack     at ChildProcess.<anonymous> (/home/pooldaemon/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
160 verbose stack     at emitTwo (events.js:126:13)
160 verbose stack     at ChildProcess.emit (events.js:214:7)
160 verbose stack     at maybeClose (internal/child_process.js:915:16)
160 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
161 verbose pkgid cryptonight-hashing@13.0.0
162 verbose cwd /home/pooldaemon
163 verbose Linux 4.9.93-mainline-rev1
164 verbose argv "/home/pooldaemon/.nvm/versions/node/v8.16.0/bin/node" "/home/pooldaemon/.nvm/versions/node/v8.16.0/bin/npm" "i" "-g" "https://github.com/MoneroOcean/node-cryptonight-hashing"
165 verbose node v8.16.0
166 verbose npm  v6.10.3
167 error code ELIFECYCLE
168 error errno 1
169 error cryptonight-hashing@13.0.0 install: `node-gyp rebuild`
169 error Exit status 1
170 error Failed at the cryptonight-hashing@13.0.0 install script.
170 error This is probably not a problem with npm. There is likely additional logging output above.
171 verbose exit [ 1, true ]

**Comment by MoneroOcean** [comment]
Should be fixed in https://github.com/MoneroOcean/node-cryptonight-hashing/releases/tag/v13.0.1 ?

**Comment by bobbieltd** [comment]
13.0.1 works. Thank you for quick support.
