### ISSUE TITLE
Dero/Astrobwt

### ISSUE THREAD

**Issue by CoFix** [MoneroOcean/node-cryptonight-hashing#43]
Hello,

Will support be added for Dero's new algorithm?

xmrig provided the necessary support. 
https://github.com/xmrig/xmrig/commit/14ef99ca67af05161080bec9a97b52b7273d72d5

**Comment by peipeiTu** [comment]
I also care about this issue!

**Comment by MoneroOcean** [comment]
Yes, I will support it. Hopefully this week.

**Comment by CoFix** [comment]
@MoneroOcean 

DERO HardFork on block 4550555,  March 7,2020. ~0200-GMT to support CPU mining.

Do you have a chance to do it before this date?

**Comment by MoneroOcean** [comment]
Yes. Done.
