### ISSUE TITLE
New BitTube CN Heavy Fork

### ISSUE THREAD

**Issue by CoFix** [MoneroOcean/node-cryptonight-hashing#8]
Hi King,

Another fork for your information.
https://github.com/ipbc-dev/node-cryptonote-util/commit/df78c197340ff53adb421e231d152c1c55ea6349
https://github.com/ipbc-dev/node-cryptonote-util/commit/1f18a2369fb77b61b4e5d2898ad239f83634fb12
https://github.com/ipbc-dev/node-cryptonote-util/commit/f36545aa3436152b42c9f1cbd55ed6b268cfb27d

Thank You.

**Comment by MoneroOcean** [comment]
Thanks for information! I usually quickly add support only if it is supported in one of https://github.com/xmrig/xmrig releases.

**Comment by travis1234** [comment]
Any update on this one @MoneroOcean ?

**Comment by MoneroOcean** [comment]
No news, since there is no released xmrig support yet.

**Comment by CoFix** [comment]
https://github.com/xmrig/xmrig-proxy/issues/238

**Comment by travis1234** [comment]
@MoneroOcean just released today https://github.com/xmrig/xmrig/releases/tag/v2.6.4

**Comment by MoneroOcean** [comment]
Nice! Implemented here as well.
